from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns=[

    path('',views.home,name='home'),
    path('login',views.login,name='login'),
    path('register',views.register,name='register'),
    path('logout',views.logout,name='logout'),
    path('profile/<int:user_id>/',views.view_profile,name='view_profile'),
    path('edit_user/',views.edit_user,name='edit_user'),
    path('employee_list',views.employee_list,name='employee_list'),
    path('add_employee/', views.add_employee, name='add_employee'),
    path('important-function/',views.important_function_view,name='important_function'),
    path('promote_to_admin/<int:user_id>/',views.promote_to_admin,name='promote_to_admin'),
    path('depromote_admin/<int:user_id>/', views.depromote_admin, name='depromote_admin'),
    path('employees/level/<str:level>/',views.employees_by_level,name='employees_by_level'),
    path('employees/skill/<str:skill>/', views.employees_by_skill,name='employees_by_skill'),
    path('create_ticket/',views.create_ticket,name='create_ticket'),
    path('user_tickets/<int:user_id>/',views.user_tickets,name='user_tickets'),
    path('profile/<int:user_id>/tickets/', views.view_tickets, name='view_tickets'),
    path('ticket/edit/<int:ticket_id>/', views.edit_ticket, name='edit_ticket'),
    path('ticket/delete/<int:ticket_id>/', views.delete_ticket, name='delete_ticket'),
    path('toggle-break/', views.toggle_break, name='toggle_break'),
    path('toggle-break-status/',views.toggle_break_status,name='toggle_break_status'),
    path('assign_ticket/<int:ticket_id>/', views.assign_ticket, name='assign_ticket'),
    path('tickets/close/<int:ticket_id>/', views.close_ticket, name='close_ticket'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('activity/daily/', views.daily_activity_view, name='daily_activity'),
    path('activity/user/<int:user_id>/', views.user_activity_view, name='user_activity'),
    path('tickets/<int:ticket_id>/start/', views.start_work, name='start_work'),
    path('tickets/<int:ticket_id>/stop/', views.stop_work, name='stop_work'),
    path('update_time_spent/', views.update_time_spent, name='update_time_spent'),
    path('update_ticket_activity/', views.update_ticket_activity, name='update_ticket_activity'),
    path('update_ticket_status/', views.update_ticket_status, name='update_ticket_status'),
    path('clear_notification/', views.clear_notification, name='clear_notification'),
    path('filter-users-by-group/', views.filter_users_by_group, name='filter_users_by_group'),
    path('mark-notification-as-read/', views.mark_notification_as_read, name='mark_notification_as_read'),
    path('dashboard/', views.dashboard, name='dashboard'),
]