# Generated by Django 5.1.1 on 2024-09-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='skill',
            field=models.CharField(choices=[('Windows', 'Windows'), ('Linux', 'Linux'), ('AWS', 'AWS'), ('OCI', 'OCI'), ('LEVELONE', 'LEVELONE')], max_length=10),
        ),
    ]
