# Generated by Django 4.2 on 2024-11-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(default='AUTO', max_length=10),
        ),
    ]
