# Generated by Django 4.2 on 2024-11-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
