# Generated by Django 5.1.1 on 2024-09-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employeeprofile_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='level',
            field=models.CharField(choices=[('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3')], max_length=1),
        ),
    ]
