# Generated by Django 4.2 on 2024-11-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_ticket_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
