# Generated by Django 5.1.1 on 2024-09-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employeeprofile_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='skill',
            field=models.CharField(choices=[('Linux', 'Linux'), ('Windows', 'Windows/Azure'), ('AWS', 'Network/AWS'), ('LEVELONE', 'Level One'), ('OCI', 'OCI')], max_length=20),
        ),
    ]
