# Generated by Django 4.2 on 2024-11-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_session_delete_useractivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
