# Generated by Django 5.1.1 on 2024-09-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employeeprofile_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='level',
            field=models.CharField(choices=[('1', 'Level 1')], max_length=10),
        ),
    ]
