# Generated by Django 4.2 on 2024-11-13 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_delete_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='break_duration',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='break_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='total_work_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
