# Generated by Django 4.2 on 2024-11-14 05:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0007_employeeprofile_break_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='break_duration',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='break_start_time',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='login_time',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='logout_time',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='total_work_time',
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('break_duration', models.DurationField(default=datetime.timedelta)),
                ('total_work_time', models.DurationField(default=datetime.timedelta)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
