# Generated by Django 4.2 on 2024-10-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_employeeprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
