# Generated by Django 4.2 on 2024-10-03 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_employeeprofile_login_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='total_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
