# Generated by Django 4.2 on 2024-11-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_dailyactivity_active_sessions_delete_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyactivity',
            name='active_sessions',
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='session_times',
            field=models.JSONField(default=list),
        ),
    ]
