# Generated by Django 4.2 on 2024-10-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_employeeprofile_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
