# Generated by Django 4.2 on 2024-10-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_employeeprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='is_on_break',
            field=models.BooleanField(default=False),
        ),
    ]
