# Generated by Django 4.2 on 2024-11-15 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_sessionactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyactivity',
            name='accumulated_work_time',
        ),
    ]
