# Generated by Django 4.2 on 2024-10-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_employeeprofile_is_on_break'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='promoted_to_admin',
            field=models.BooleanField(default=False),
        ),
    ]
