# Generated by Django 4.2 on 2024-11-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_remove_dailyactivity_accumulated_work_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionactivity',
            name='break_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
