# Generated by Django 4.2 on 2024-11-18 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_sessionactivity_break_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='time_spent',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='ticket',
            name='work_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
