# Generated by Django 4.2 on 2024-10-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_ticket_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('waiting_on_customer', 'Waiting on Customer'), ('initial_response', 'Initial Response')], max_length=50),
        ),
    ]
