# Generated by Django 4.2 on 2024-11-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_ticket_time_spent_ticket_work_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
