# Generated by Django 4.2 on 2024-11-21 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_ticket_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='break_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='ticket',
            name='break_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
